### ISSUE TITLE
Using traefik doesn't work

### ISSUE THREAD

**Issue by titansmc** [prabhatsharma/apache-guacamole-helm-chart#6]
Hi,
I am using Traefik in front of it (it is supposed to handle websockets without any special configuration), do I need to do anything special? I get:

```
10:00:40.874 [http-nio-8080-exec-3] INFO  o.a.g.tunnel.TunnelRequestService - User "guacadmin" connected to connection "1".
10:00:40.986 [http-nio-8080-exec-1] INFO  o.a.g.tunnel.TunnelRequestService - User "guacadmin" disconnected from connection "1". Duration: 112 milliseconds
Exception in thread "Thread-44" java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:424)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:191)
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.sendInstruction(GuacamoleWebSocketTunnelEndpoint.java:152)
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.access$200(GuacamoleWebSocketTunnelEndpoint.java:53)
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint$2.run(GuacamoleWebSocketTunnelEndpoint.java:253)
^C
```

**Comment by r1cebank** [comment]
switch to traefik or use nginx with websocket support

**Comment by titansmc** [comment]
I am already using Traefik

**Comment by r1cebank** [comment]
Sorry i forgot to include the version, use traefik v2, it has websocket support V1 doesnt

**Comment by titansmc** [comment]
I am running the latet v2. However, I don't need Guacamole at the moment.
Thanks.
